version: '3'
services:
  redis:
    build: ./infraestructure/docker/redis
    image: redis
    ports:
      - "6379:6379"
    env_file:
     - ./infraestructure/environments/development/variables.env
    volumes:
      - /data/redis:/data
    command: redis-server --appendonly yes
  http:
    build: ./infraestructure/docker/nginx
    image: nginx
    volumes:
      - "./infraestructure/docker/nginx/mysite.conf:/etc/nginx/conf.d/mysite.conf"
      - "./src:/code"
    env_file:
     - ./infraestructure/environments/development/variables.env
    ports:
      - "8085:80"
    command: /bin/bash -c "cat /etc/nginx/conf.d/mysite.conf > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    depends_on:
      - php-fpm
  php-fpm:
    build: ./infraestructure/docker/php
    image: php-fpm
    env_file:
     - ./infraestructure/environments/development/variables.env
    volumes:
      - "./src:/code"
